os: linux
dist: focal
arch: ppc64le
group: stable
language: minimal
# ruby:
#   - 3.0.0
#   - 3.0.1
#   - 3.0.2
#   - 2.7.7
#   - 2.7.6  
install: skip
script:
  - ruby -v
  - bundle -v
  - cat /etc/os-release
  - cat /etc/hosts
