dist: bionic
group: previous

jobs:
  include:
    - arch: arm64
    # - arch: ppc64le      
    # - arch: s390x
    # - arch: amd64
    
# group: edge
language: python

# go:
# - master


script:
  - uname -a
  - python3 -m pip install coverage
  - cat /etc/hosts
